#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist on \
	window_shadow on \
	window_animation_duration 0.15 \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.90 \
	window_opacity off \
	insert_feedback_color 0xffd75f5f \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 8 \
	bottom_padding 8 \
	left_padding 8 \
	right_padding 8 \
	window_gap 06 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

# set 1 to float
yabai -m config --space 1 layout float

# window locations
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Raycast Settings$" manage=off
yabai -m rule --add app="Exam4" manage=off
yabai -m rule --add app="^iTerm2$" manage=off
# yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="Zotero" manage=off
yabai -m rule --add "Zoom Workspace" space=1 manage=off
yabai -m rule --add app="Arc" title="^$" space=2 mouse_follows_focus=off
yabai -m rule --add app="Zen Browser" space=2
yabai -m rule --add app="Safari" space=2
yabai -m rule --add app="Obsidian" space=3
yabai -m rule --add app="Acrobat" space=4
yabai -m rule --add app="^Emacs$" space=5
yabai -m rule --add app="Word" space=5
yabai -m rule --add app="Feishin" space=6
yabai -m rule --add app="Aonsoku" space=6
yabai -m rule --add app="^Calendar$" space=7
yabai -m rule --add app="^Discord$" space=7
yabai -m rule --add app="^Visual Studio Code$" space=8
#yabai -m rule --add app="Zotero" space=7
yabai -m rule --add app="Mail" space=9
echo "yabai configuration loaded.."
