[mgr]
prepend_keymap = [
  { on = ["R","b"], run = "plugin recycle-bin",desc = "Open Recycle Bin menu" },
  { on = [";"],     run = "plugin bunny",      desc = "Start bunny.yazi" },
  { on = ["R","f"], run = "plugin duck-radar", desc = "🦆 Duck Radar - Recent Files" },
  { on = ["C"],     run = "plugin ouch",       desc = "Compress with ouch" },
  { on = ["<C-y>"], run = "plugin system-clipboard", desc="Use System Clipboard"},
  { on = "<C-n>", run = "shell -- ripdrag -x %s1" },
  # Toggle Hidden
  { on = ".", run = [ "hidden toggle", "plugin pref-by-location -- save" ], desc = "Toggle the visibility of hidden files" },

  # Linemode
  { on = [ "m", "s" ], run = [ "linemode size", "plugin pref-by-location -- save" ],        desc = "Linemode: size" },
  { on = [ "m", "p" ], run = [ "linemode permissions", "plugin pref-by-location -- save" ], desc = "Linemode: permissions" },
  { on = [ "m", "b" ], run = [ "linemode btime", "plugin pref-by-location -- save" ],       desc = "Linemode: btime" },
  { on = [ "m", "m" ], run = [ "linemode mtime", "plugin pref-by-location -- save" ],       desc = "Linemode: mtime" },
  { on = [ "m", "o" ], run = [ "linemode owner", "plugin pref-by-location -- save" ],       desc = "Linemode: owner" },
  { on = [ "m", "n" ], run = [ "linemode none", "plugin pref-by-location -- save" ],        desc = "Linemode: none" },
  # Custom size_and_mtime linemode
  # { on = [ "u", "S" ], run = [ "linemode size_and_mtime", "plugin pref-by-location -- save" ], desc = "Show Size and Modified time" },

  # lazygit plugin
  { on   = [ "g", "i" ], run  = "plugin lazygit", desc = "run lazygit" },
   
  # chezmoi plugin
  { on   = ["g", "C", "a" ], run  = "plugin chezmoi add", desc = "Chezmoi add" },
  { on   = ["g", "C", "A" ], run  = "plugin chezmoi add-encrypt", desc = "Chezmoi add (encrypted)" },
  { on   = ["g", "C", "r" ], run  = "plugin chezmoi re-add", desc = "Chezmoi re-add" },
  { on   = ["g", "C", "e" ], run  = "plugin chezmoi edit", desc = "Chezmoi edit source" },
  { on   = ["g", "C", "d" ], run  = "plugin chezmoi diff", desc = "Chezmoi diff" },
  { on   = ["g", "C", "p" ], run  = "plugin chezmoi apply", desc = "Chezmoi apply" },
  { on   = ["g", "C", "s" ], run  = "plugin chezmoi status", desc = "Chezmoi status" },
  { on   = ["g", "C", "m" ], run  = "plugin chezmoi managed", desc = "Chezmoi managed (fzf)" },
  { on   = ["g", "C", "u" ], run  = "plugin chezmoi unmanaged", desc = "Chezmoi unmanaged (fzf)" },
  { on   = ["g", "C", "f" ], run  = "plugin chezmoi forget", desc = "Chezmoi forget" },
  { on   = ["g", "C", "g" ], run  = "plugin chezmoi goto", desc = "Chezmoi goto source/target" },

  # Sorting
  # Any changes during disabled state won't be saved to save file.
  { on = [ ",", "t" ], run = "plugin pref-by-location -- toggle",                                                desc = "Toggle auto-save preferences" },
  { on = [ ",", "d" ], run = "plugin pref-by-location -- disable",                                               desc = "Disable auto-save preferences" },
  # This will reset any preference changes for the current working directory (CWD),
  # then fall back to the predefined preferences in init.lua or yazi.toml.
  { on = [ ",", "R" ], run = [ "plugin pref-by-location -- reset" ],                                             desc = "Reset preference of cwd" },
  { on = [ ",", "m" ], run = [ "sort mtime --reverse=no", "linemode mtime", "plugin pref-by-location -- save" ], desc = "Sort by modified time" },
  { on = [ ",", "M" ], run = [ "sort mtime --reverse", "linemode mtime", "plugin pref-by-location -- save" ],    desc = "Sort by modified time (reverse)" },
  { on = [ ",", "b" ], run = [ "sort btime --reverse=no", "linemode btime", "plugin pref-by-location -- save" ], desc = "Sort by birth time" },
  { on = [ ",", "B" ], run = [ "sort btime --reverse", "linemode btime", "plugin pref-by-location -- save" ],    desc = "Sort by birth time (reverse)" },
  { on = [ ",", "e" ], run = [ "sort extension --reverse=no", "plugin pref-by-location -- save" ],               desc = "Sort by extension" },
  { on = [ ",", "E" ], run = [ "sort extension --reverse", "plugin pref-by-location -- save" ],                  desc = "Sort by extension (reverse)" },
  { on = [ ",", "a" ], run = [ "sort alphabetical --reverse=no", "plugin pref-by-location -- save" ],            desc = "Sort alphabetically" },
  { on = [ ",", "A" ], run = [ "sort alphabetical --reverse", "plugin pref-by-location -- save" ],               desc = "Sort alphabetically (reverse)" },
  { on = [ ",", "n" ], run = [ "sort natural --reverse=no", "plugin pref-by-location -- save" ],                 desc = "Sort naturally" },
  { on = [ ",", "N" ], run = [ "sort natural --reverse", "plugin pref-by-location -- save" ],                    desc = "Sort naturally (reverse)" },
  # --sensitive=no or --sensitive
  # { on = [ ",", "N" ], run = [ "sort natural --reverse=no --sensitive", "plugin pref-by-location -- save" ],                    desc = "Sort naturally" },
  { on = [ ",", "s" ], run = [ "sort size --reverse=no", "linemode size", "plugin pref-by-location -- save" ],   desc = "Sort by size" },
  { on = [ ",", "S" ], run = [ "sort size --reverse", "linemode size", "plugin pref-by-location -- save" ],      desc = "Sort by size (reverse)" },
  { on = [ ",", "r" ], run = [ "sort random --reverse=no", "plugin pref-by-location -- save" ],                  desc = "Sort randomly" },
]
